#!/bin/bash

# Welcome to the Kickstarter laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "Setup failed.\n\n" >&2; exit $ret' EXIT

set -e

##
# Install XCode and XCode Command line tools
if [ ! -d /Applications/Xcode.app ]
then
  XCODE_URL='http://itunes.apple.com/us/app/xcode/id497799835'
  echo "Missing XCode. Install XCode from the Mac App Store:"
  echo $XCODE_URL
  open $XCODE_URL
  exit 1
fi

# need a way to check for this and automate:
# sudo xcodebuild -license

# XCode command-line tools
# From http://stackoverflow.com/a/15371967
while ! pkgutil --pkg-info=com.apple.pkg.CLTools_Executables > /dev/null; do

  if [ -z "$xcode_cli_installing" ]; then
    echo "Installing XCode command line tools."
    xcode-select --install
    echo "Waiting XCode command line tools..."
    xcode_cli_installing='yes'
  else
    sleep 1
  fi

done

##
# Install homebrew
if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Checking Homebrew formulae ..."
brew bundle --file=- > /dev/null <<EOF
tap "homebrew/services"

brew "git"
brew "openssl"
brew "rbenv"
brew "ruby-build"
EOF

fancy_echo "Configuring rbenv init ..."
eval "$(rbenv init -)"

fancy_echo "Restarting background brew updater..."
##
# Automatically run `brew update` every 2 hours
# This saves ~20 seconds on subsequent runs b/c we don't have to wait for `brew update`
cat > ~/Library/LaunchAgents/com.kickstarter.brew-updater.plist <<- EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.kickstarter.homebrew-updater</string>
    <key>ProgramArguments</key>
    <array>
    <string>/usr/local/bin/brew</string>
    <string>update</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>StartInterval</key>
    <integer>7200</integer>
  </dict>
</plist>
EOF

launchctl unload ~/Library/LaunchAgents/com.kickstarter.brew-updater.plist 2> /dev/null
launchctl load   ~/Library/LaunchAgents/com.kickstarter.brew-updater.plist

##
# source ~/.ksr.rc from shell's rc file
case $(basename "$SHELL") in
  bash )
    profile="$HOME/.bashrc"
    ;;
  zsh )
    profile="$HOME/.zshrc"
    ;;
  * )
    echo 'Unrecognized shell'
    ;;
  esac

cmd='if [ -e ~/.ksr.rc ]; then source ~/.ksr.rc; fi # Provisioned by ksr laptop script'
if ! grep -Fqs "$cmd" "$profile"; then
  fancy_echo "Adding ~/.ksr.rc to $profile"
  printf "\n$cmd\n" >> "$profile"
fi

cat > ~/.ksr.rc <<-"EOF"
# Kickstarter init commands provisioned by the laptop script.
# Changes will be overwritten.

# Initialize rbenv
eval "$(rbenv init -)"

if [[ ! "$PATH" =~ "/usr/local/bin" ]]; then
  export PATH="/usr/local/bin:$PATH"
fi

# Set a higher ulimit to avoid
# capistrano issues deploying to many servers
LIMIT=2048
if [ $LIMIT -gt `ulimit -n` ]; then
   ulimit -n $LIMIT
fi
EOF


fancy_echo "Laptop setup succeeded."
